# permissions for end users to view createdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: createdeployment-viewer-role
rules:
- apiGroups:
  - cache.lilqcn
  resources:
  - createdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.lilqcn
  resources:
  - createdeployments/status
  verbs:
  - get
